services:
  postgres:
    image: postgres
    container_name: AiAgregator-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=AIA-BE
    ports:
      - "5444:5432"
    volumes:
      - aiagregatordata:/var/lib/postgresql/data

  backend:
    build:
      context: backend
    container_name: AiAgregator-backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    env_file:
      - backend/.env
    depends_on:
      - postgres
    ports:
      - "3001:3001"

  frontend:
    build:
      context: frontend
    container_name: AiAgregator-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    env_file:
      - frontend/.env
    depends_on:
      - backend

volumes:
  aiagregatordata:
